blank_issues_enabled: false
contact_links:
  - name: Support for new devices
    about: We are not currently taking new device requests. Please send a pull request instead.
  - name: Ask questions or support
    url: https://discord.gg/GyCBjQhqCd
    about: Engage in our community on Discord
